### ISSUE TITLE
Error  while loading the theme.

### ISSUE THREAD

**Issue by vrnithinkumar** [SeanCline/Npp-VS2012-Dark#12]
![capture](https://cloud.githubusercontent.com/assets/1416699/11293091/8867df2e-8f7c-11e5-8613-9d5525858b13.PNG)

OS : Wiindows 7 64 bit
Notepad++ Version: v6.8.6

**Comment by SeanCline** [comment]
Github's interface is kinda silly when it comes to downloading a single file. Chances are you didn't the the 'raw' version of the file so it has some html hanging around in it.

Other people reported the same thing in previous issues.

Try downloading it by right clicking on the link embedded in the readme, or by navigating to the [VS2012-Dark.xml](https://github.com/SeanCline/Npp-VS2012-Dark/blob/master/VS2012-Dark.xml) page and clicking 'raw'.

If that doesn't work, let me know and I'll look into it but stylers are still working for me in v6.8.6

**Comment by vrnithinkumar** [comment]
Awesome. Its working now. Thank you very much.
