### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by royalbisht** [SeanCline/Npp-VS2012-Dark#13]
![screenshot_1](https://cloud.githubusercontent.com/assets/16011976/11390193/985e7290-936d-11e5-8ad1-8e8225b1bba7.png)

**Comment by SeanCline** [comment]
Make sure you get the raw version of [VS2012-Dark.xml](https://raw.githubusercontent.com/SeanCline/Npp-VS2012-Dark/master/VS2012-Dark.xml), otherwise GitHub's markup make's its way into the download.

**Comment by royalbisht** [comment]
I have saved it by right click > save. I m using Google Chrome.

**Comment by SeanCline** [comment]
Can you open the saved file and see if it's valid XML?
Does the file start out with `<?xml version="1.0" encoding="Windows-1252" ?>` or is something else there?
