### ISSUE TITLE
"Edge colour" not visible

### ISSUE THREAD

**Issue by ffes** [SeanCline/Npp-VS2012-Dark#14]
"Edge colour" is the color used by "Settings", "Preference", "Editing", "Vertical edge settings".

At the moment this color is not visible. I suggest to make the colors the same as the caret colors.

**Comment by SeanCline** [comment]
Good catch.

I changed it to be the same as the `Indent guideline style` so when it is in `Background mode`, the text is at least halfway readable. If you take offense to the colour I used, let me know.
