### ISSUE TITLE
CSS: fontName=Batang

### ISSUE THREAD

**Issue by ffes** [SeanCline/Npp-VS2012-Dark#15]
In the CSS comment entry ([line 216](https://github.com/SeanCline/Npp-VS2012-Dark/blob/master/VS2012-Dark.xml#L266)) the fontName "Batang" is used. I assume this is not by-design.

**Comment by ffes** [comment]
Oops, submitted too fast...
The line number is 266, the link is correct. And it is the "TAG" entry.

**Comment by SeanCline** [comment]
That was very much *not* intentional. Funny thing, I actually noticed that the font looked different a couple months back but the Style Configurator didn't show anything out of the ordinary so I assumed I was just going crazy.
