### ISSUE TITLE
"Load stylers.xml failed!"

### ISSUE THREAD

**Issue by narutoreplicate** [SeanCline/Npp-VS2012-Dark#17]
When I select your theme, I get prompted with a error message, "Load stylers.xml failed!" I have the latest version of Notepad++ 6.8.8, and I can confirm that other themes work, including downloaded custom themes.

Any suggestions?

**Comment by SeanCline** [comment]
Can you take a look at issue #1 and see if it explains your problem?

**Comment by narutoreplicate** [comment]
Hey dude! Sorry for the late delay; this solution worked for me. Thank you very much. I didn't realize there was a "closed" tab under issues, so I didn't see issue #1 when I looked for it.
