### ISSUE TITLE
load stylers.xml failed!

### ISSUE THREAD

**Issue by fets** [SeanCline/Npp-VS2012-Dark#20]
Hi
I have problem 

![2016-10-26_23-31-12](https://cloud.githubusercontent.com/assets/512138/19744139/d3d29bd8-9bd4-11e6-868d-391ef6872a68.png)

version notepad++ 6.9.2.0

Thanks!

**Comment by yourbuddypal** [comment]
Can you take a look at issue [#1](https://github.com/SeanCline/Npp-VS2012-Dark/issues/1) and see if it explains your problem?

**Comment by fets** [comment]
Thanks for the help! Now work its fine!
