### ISSUE TITLE
Stylers.xml failed...

### ISSUE THREAD

**Issue by tdog123** [SeanCline/Npp-VS2012-Dark#8]
Hi - I like your theme, but I get this error when I selected the theme in the style configurator:

Load stylers.xml failed!

Tom

**Comment by SeanCline** [comment]
Can you make sure you got the raw xml version of the file without GitHub's html tacked onto it?

Issue #3 has some more information.

**Comment by tdog123** [comment]
Definitely solved it. Thanks. I should have looked at the other issues, but I thought for SURE that couldn't be the problem :-)
